version: "4.13.1"
services:
  pdf-analyzer:
    build: .
    links:
      - grobid  
    volumes:
      - type: bind
        source: ./Files
        target: /app/Files
  grobid:
    image: lfoppiano/grobid:0.7.2
    restart: always
    ports:
      - "8070:8070"
    environment:
      - GROBID__SERVICE__MAXTHREADPOOL=10
  
